export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED'

export const SIGN_IN = 'SIGN_IN'
export const SET_CERRENT_USER = 'SET_CERRENT_USER'
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'

export const LOG_OUT = 'LOG_OUT'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const LOG_OUT_FAILED = 'LOG_OUT_FAILED'

export const GET_KITCHEN = 'GET_KITCHEN'
export const GET_KITCHEN_SUCCESS = 'GET_KITCHEN_SUCCESS'
export const GET_KITCHEN_FAILED = 'GET_KITCHEN_FAILED'

export const ADD_KITCHEN = 'ADD_KITCHEN'
export const ADD_KITCHEN_SUCCESS = 'ADD_KITCHEN_SUCCESS'
export const ADD_KITCHEN_FAILED = 'ADD_KITCHEN_FAILED'

export const DEL_KITCHEN = 'DEL_KITCHEN'
export const DEL_KITCHEN_SUCCESS = 'DEL_KITCHEN_SUCCESS'
export const DEL_KITCHEN_FAILED = 'DEL_KITCHEN_FAILED'

export const EDIT_KITCHEN = 'EDIT_KITCHEN'
export const EDIT_KITCHEN_SUCCESS = 'EDIT_KITCHEN_SUCCESS'
export const EDIT_KITCHEN_FAILED = 'EDIT_KITCHEN_FAILED'

export const GET_RESTARAN = 'GET_RESTARAN'
export const GET_RESTARAN_SUCCESS = 'GET_RESTARAN_SUCCESS'
export const GET_RESTARAN_FAILED = 'GET_RESTARAN_FAILED'

export const GET_REST = 'GET_REST'
export const GET_REST_SUCCESS = 'GET_REST_SUCCESS'
export const GET_REST_FAILED = 'GET_REST_FAILED'

export const ADD_RESTARAN = 'ADD_RESTARAN'
export const ADD_RESTARAN_SUCCESS = 'ADD_RESTARAN_SUCCESS'
export const ADD_RESTARAN_FAILED = 'ADD_RESTARAN_FAILED'

export const DEL_RESTARAN = 'DEL_RESTARAN'
export const DEL_RESTARAN_SUCCESS = 'DEL_RESTARAN_SUCCESS'
export const DEL_RESTARAN_FAILED = 'DEL_RESTARAN_FAILED'

export const EDIT_RESTARAN = 'EDIT_RESTARAN'
export const EDIT_RESTARAN_SUCCESS = 'EDIT_RESTARAN_SUCCESS'
export const EDIT_RESTARAN_FAILED = 'EDIT_RESTARAN_FAILED'

export const GET_REV = 'GET_REV'
export const GET_REV_SUCCESS = 'GET_REV_SUCCESS'
export const GET_REV_FAILED = 'GET_REV_FAILED'

export const ADD_REV = 'ADD_REV'
export const ADD_REV_SUCCESS = 'ADD_REV_SUCCESS'
export const ADD_REV_FAILED = 'ADD_REV_FAILED'

export const DEL_REV = 'DEL_REV'
export const DEL_REV_SUCCESS = 'DEL_REV_SUCCESS'
export const DEL_REV_FAILED = 'DEL_REV_FAILED'

export const ADD_FAVORITE = 'ADD_FAVORITE'
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS'
export const ADD_FAVORITE_FAILED = 'ADD_FAVORITE_FAILED'

export const GET_FAVORITE = 'GET_FAVORITE'
export const GET_FAVORITE_SUCCESS = 'GET_FAVORITE_SUCCESS'
export const GET_FAVORITE_FAILED = 'GET_FAVORITE_FAILED'

export const GET_ORDER = 'GET_ORDER'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED'

export const ADD_ORDER = 'ADD_ORDER'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_FAILED = 'ADD_ORDER_FAILED'